### ISSUE TITLE
Handbrake Encoding Failing

### ISSUE THREAD

**Issue by bryanmcain** [mackworth/cTiVo#420]
Hi,  

Sorry for my lack of response on the last issue I had opened.  I'll keep up with this one.

I am seeing failures when trying to encode via HB.  Download to decrypted tivo show works fine, FFMPEG seems to work OK, but when I try to encode with a custom HB profile, it fails.

Of note, when I go into settings and try to edit a handbrake format, and hit the dropdown for built in HB formats, at the bottom of the list where I would normally see custom saved formats it says: "handbrake has exited." which seems like its probably not right.

Let me know what you need to see to troubleshoot this.  Thanks in advance.

**Comment by mackworth** [comment]
That’s interesting. CTiVo launches Handbrake to get the list of built-in HB formats, so it sounds like that’s failing. Can you Exit cTiVo, restart, set debug to verbose, then go into the edit formats and pull down the menu. Then use Help>show logs in finder and compress (right click in Finder) the most recent, and post that here. 

Which MacOS are you running?

**Comment by bryanmcain** [comment]
Done.
[Archive.zip](https://github.com/mackworth/cTiVo/files/4689332/Archive.zip)

**Comment by bryanmcain** [comment]
Mojave, 10.14.6

**Comment by bryanmcain** [comment]
Sorry, use this one instead.
[Archive.zip](https://github.com/mackworth/cTiVo/files/4689362/Archive.zip)

**Comment by mackworth** [comment]
So the "Handbrake has exited" has apparently been added to the recent versions, so when I updated the last time, that started appearing. You're still seeing all the built-ins and your custom ones, correct?  So just ignore that line; I'll fix it next release.

As for the handbrake Format failure, it's saying that you have some kind of syntax error. You'll need to run a show with Debug at Detail to get the exact syntax that's being given to Handbrake, unfortunately, the error msg is lost in the log because due to the syntax error, Handbrake is printing out its whole help file (of which cTiVo only displays the last page or so).

Finally, I will gratuitously note that you may be having some network issues. You've got shows retrying, you've got devices appearing and disappearing regularly. 

(p.s. be sure to turn Debug back to Normal or Major when done; Verbose in particular slows things down)

**Comment by bryanmcain** [comment]
I do not see my Custom presets in the dropdown.  Those custom presets were created in the GUI app - which is not located where cTivo says it found the handbrake CLI.  Is that important?

I will try downloading with Detail on now.

**Comment by mackworth** [comment]
It shouldn't matter, the presets are stored in ~/Library/Application\ Support/HandBrake/UserPresets.json, so should be the same regardless of which app you use to edit/access them.  

Try this:

-    In Finder, right-click on your cTiVo app, and "Show folder contents"
-   Open Contents, then MacOS folders
-   Run Terminal
-   drag HandBrakeCLI from MacOS folder into the Terminal window (should put filepath on command line)
-   add `  --preset-import-gui  --preset-list` after the filepath (note space at beginning and between)
-   hit return
-   See if your custom presets are at the bottom of the list.

**Comment by bryanmcain** [comment]
I do not have any custom presets in that list.

**Comment by mackworth** [comment]
that is correct! 🥳

Sigh, apparently Handbrake 1.3 moved the location of the presets, and once you run it, their earlier CLI can't find them. I'll have to update the CLI in cTiVo to make it work again.

The good news is that cTiVo's use of the user presets is only to fill in the visible fields. So, you can create a Format with the new CLI yourself in the meantime.  [Download it here](https://github.com/HandBrake/HandBrake/releases/download/1.3.2/HandBrakeCLI-1.3.2.dmg): 

Then your Format `Encoder To Use` should point to THAT version. Next, select any preset (e.g. Fast 720p30), then change `Video Options for Encoder` from `-Z"Fast 720p30"` to `--preset-import-gui -Z"YOURPRESETNAME"` That should do it.

**Comment by bryanmcain** [comment]
I dropped the new version into the cTivo app, seems to have fixed the problem.  I can see my custom presets now.  Of course, my bolt is not showing up in cTivo right now so I can't do an end to end test until my wife is done watching TV and I can reboot the Tivo.

Most of the network problems you identified earlier seem to be limited to the Bolt, and a reboot usually fixes the problem.

**Comment by bryanmcain** [comment]
Nevermind, download still fails.  I'll post a log tomorrow.  Thanks for your help.

**Comment by mackworth** [comment]
You can run a test in the GUI. Just download a show using the Decrypted Format and then process it. 

That Format will result in the file that cTiVo would then hand to Handbrake.

**Comment by bryanmcain** [comment]
[com.cTiVo.cTiVo 2020-05-28--11-00-01-956.log](https://github.com/mackworth/cTiVo/files/4695722/com.cTiVo.cTiVo.2020-05-28--11-00-01-956.log)

**Comment by bryanmcain** [comment]
Decrypted Tivo Show format always works - I don't usually later encrypt with handbrake in that scenario.

**Comment by mackworth** [comment]
So your log shows 
`LaunchPath: /Applications/cTiVo.app/Contents/MacOS/HandBrakeCLI --preset-import-gui -Z 'bryan's default' -o '/Volumes/videos/TV Shows/Supergirl/Season 05/Supergirl - S05E19 - Immortal Kombat.mp4' -i '/var/folders/v3/234ws10d6m9681mmz_vryv740000gp/T/ctivo/bufferSupergirl - S05E19 - Immortal Kombat.mpg'`

So, that's obvious, the single-quote inside the quoted preset name is a problem, so it thinks it's got `bryan` for a preset with an extra `s default` hanging around. Easy fix and easy workaround: take out the quote mark

But wait! I remember testing that. 
 _Goes to read code_ 
Yes, it handles that properly. 
 _Tries it on my machine with the new CLI; it fails_
So that matches his issue 
 _Creates a new preset without the quote; still fails_
Weird
_Tries a single word without any special chars; still fails_ 
Very weird 
 _Goes off to ask a question on Handbrake Forum; Finds a known problem in 1.3.2.   Sigh.... _

So the answer is that (a) 1.3 broke the older CLI; 1.2.2 CLI can't access user presets from the 1.3 GUI  and then (b) 1.3.2 broke accessing those presets.  

As a workaround, you can either download 1.3.1 CLI OR, use the full path for the preset in the -Z parameter:  `-z "My Presets/Bryan's preset"  I've tried that on my system, and it works fine.

**Comment by bryanmcain** [comment]
Rolling back to CLI 1.3.1 seems to have fixed the problem.  A download is encoding now.

Thanks!

**Comment by mackworth** [comment]
I've released 3.4.2 beta, including HandbrakeCLI 1.3.3, which should fix this preset issue.
